%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
image_topic: "/left_camera/image"

CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [863.590518437255, 0.116814496662654, 621.666074631063,
         0, 863.100180533059, 533.971978652819,
         0, 0, 1]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.0944205499243979, 0.0946727677776504, -0.00807970960613932, 8.07461209775283e-05, 6.52716646875879e-05]

Camera.width: 1280
Camera.height: 1024

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  # if AVIA is the base LiDAR
  data: [0,-1,0,0,
         0,0,-1,0,
         1,0,0,0,
         0,0,0,1]
  # if MID is the base LiDAR
  # data: [0,1,0,0,
  #        0,0,-1,0,
  #        -1,0,0,0,
  #        0,0,0,1]