%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
image_topic: "/right_camera/image"

CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [863.081687640302, 0.176140650303666, 628.941349825503,
         0, 862.563371991533, 533.002909535090,
         0, 0, 1]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [-0.0943795554942897, 0.0982998241524913, -0.0125418048527694, 0.000456235380677041, -8.73113795357082e-05]

Camera.width: 1280
Camera.height: 1024

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  # if AVIA is the base LiDAR
  data: [0,-1,0,0,
         0,0,-1,0,
         1,0,0,0,
         0,0,0,1]
  # if MID is the base LiDAR
  # data: [0,1,0,0,
  #        0,0,-1,0,
  #        -1,0,0,0,
  #        0,0,0,1]