%YAML:1.0

LiDARNumber: 3
ImageNumber: 3
# DataPath: "/home/lqh/ros/r3live_ws/src/mersys/calib/mlcc/single_test/"
DataPath: "/home/uestc/colive_ws/src/mersys_dev/calib/mlcc/single_test/"
CameraFoV: 100

# Params for Canny Edge Extraction
Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 3
Voxel.eigen_ratio: 0.05
Voxel.down_sample_size: 0.02
Plane.min_points_size: 60
Plane.normal_theta_min: 10
Plane.normal_theta_max: 170
Plane.max_size: 4
Ransac.dis_threshold: 0.03
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.05
Edge.max_dis_threshold: 0.08

# Params for color point clouds
Color.dense: 10
Color.intensity_threshold: 10
