%YAML:1.0

#--------------------------------------------------------------------------------------------
# System Control
#--------------------------------------------------------------------------------------------
# sys.output_path: /home/lqh/ros/r3live_ws/output
# sys.output_path: /home/uestc/colive_ws/output
sys.save_frames: 0
sys.threads_pool: 20
# Number of threads used for optimization routines
sys.threads_server: 8

sys.covis_thres: 10 # Threshold for min. number of shared edges to include a covisibility edge

# Format for the trajectory output file
sys.trajectory_format: 'TUM' # {EUROC|TUM}
# EUROC: EuRoC format - stamp[ns], tx, ty, tz, qw, qx, qy, qz
# TUM: TUM format - stamp[s] tx ty tz qx qy qz qw

#--------------------------------------------------------------------------------------------
# Data input
#--------------------------------------------------------------------------------------------

# maps are loaded from here (use absolute path)
sys.map_path0: '/home/uestc/colive_ws/output/map_data'

#--------------------------------------------------------------------------------------------
# Features
#--------------------------------------------------------------------------------------------

feat.type: 'ORB' # this allows to integrate other PR algorithms. Currently, only 'ORB' and 'SIFT 'is supported
feat.desc_length: 32 # [Byte] COVINS-ORB: 32, SIFT: 128 (SIFT is only supported while using COVINS_G)

feat.num_octaves: 1 # Number of levels in the scale pyramid
feat.scale_factor: 1.0 # Scale factor between levels in the scale pyramid

#--------------------------------------------------------------------------------------------
# (COVINS_G) Feature Matching
#--------------------------------------------------------------------------------------------

extractor.img_match_thres: 40.0 # Use 30-40 for ORB Features (Hamming Distance) and use 500 for SIFT Features
extractor.ratio_thres: 0.8 # Ratio test threshold for feature Matching (Use 1 if you want to disable this)

#--------------------------------------------------------------------------------------------
# (COVINS) Feature Matching
#--------------------------------------------------------------------------------------------

matcher.desc_matching_th_low: 50
matcher.desc_matching_th_high: 100

matcher.search_radius_SE3: 9.5
matcher.search_radius_proj: 10.0
matcher.search_radius_fuse: 10.0

#--------------------------------------------------------------------------------------------
# (COVINS) Mapping 
#--------------------------------------------------------------------------------------------

mapping.activate_lm_culling: 1

mapping.kf_culling_th_red: 0.95 # redundancy threshold for callback
mapping.kf_culling_max_time_dist: 1.0 #s - max. allowed time distance between 2 consecutive KFs. Constraint for redundancy removal

#--------------------------------------------------------------------------------------------
# Place Recognition Parameters
#--------------------------------------------------------------------------------------------

# activate / deactivate place recognition
placerec.active: 1

placerec.type: 'COVINS_G' # this allows to integrate other PR algorithms. Cuurently, only 'COVINS' and 'COVINS_G' is supported

placerec.start_after_kf: 7 # map matching skips the first x KFs after map initialization
placerec.consecutive_loop_dist: 5 # after finding a loop, the next x KFs are not considered loop closure query
placerec.min_loop_dist: 100 # minimum number of KFs between the two ends of the loop to accept loop
placerec.cov_consistency_thres: 3
placerec.matches_thres: 25
placerec.matches_thres_merge: 25

placerec.exclude_kfs_with_id_less_than: 7
placerec.inter_map_matches_only: 0

# (COVINS)
placerec.inliers_thres: 20
placerec.total_matches_thres: 40

# (COVINS) RANSAC Parameters
placerec.ransac.min_inliers: 6 #def 6
placerec.ransac.probability: 0.99
placerec.ransac.max_iterations: 300
placerec.ransac.class_threshold: 25 #def:25 - threshold for inlier classification

# (COVINS_G) Parameters for 17 PT (non_central_rel_pose)
placerec.nc_rel_pose.rp_error: 1.5 # Reprojection Error in Pixels for solving 17PT
placerec.nc_rel_pose.rp_error_cov: 10 # Reprojection Error in Pixels for Cov Matrix Score
placerec.nc_rel_pose.min_inliers: 100 # Min inliers for succesful Ransac solution
placerec.nc_rel_pose.max_iters: 4000 # Ransac Max Iteration
placerec.nc_rel_pose.cov_thres: 10 #Max Covariance Matrix trace for accepting loop
placerec.nc_rel_pose.cov_iters: 30 #No. of entries in the covariance Matrix
placerec.nc_rel_pose.cov_max_iters: 300 #Max permissible iterations for building the covariance Matrix

# (COVINS_G) Parameters for 5 PT (rel_pose)
placerec.rel_pose.error_thres: 16 # threshold for inlier classification
placerec.rel_pose.min_inliers: 20 # Min inliers for succesful Ransac solution
placerec.rel_pose.max_iters: 200 # Ransac Max Iteration
placerec.rel_pose.min_img_matches: 20 # Min image matches required to proceed for 5 PT Ransac

# (COVINS_G) Yaw and Translation Thresholds to accept Loop
placerec.max_yaw: 50.0 # Maximum TF yaw (degrees) to accept Loop
placerec.max_trans: 2.0 # Maximum Translation to accept Loop

#--------------------------------------------------------------------------------------------
# Optimization
#--------------------------------------------------------------------------------------------


# (COVINS) GBA
opt.gba_iteration_limit: 10 # GBA max iterations
opt.gba_use_map_loop_constraints: 1
opt.th_outlier_align: 1.3
opt.th_gba_outlier_global: 0.92

# PGO
opt.pgo_iteration_limit: 10 # PGO max iterations
opt.perform_pgo: 1 # Enable Pose graph Optimization
opt.use_nbr_kfs: 1 # Use extra Neighboring KFs in the pose graph
opt.use_robust_loss: 1 # Use robust loss function for the loop edges

opt.pgo_fix_kfs_after_gba: 1 # KFs that were part of a GBA are fixed in future PGO runs
opt.pgo_fix_poses_loaded_maps: 0
opt.gba_fix_poses_loaded_maps: 0

# PGO Weights for KF edge constraints (Computed using Expected Accuracy)
opt.wt_kf_R: 10 
opt.wt_kf_T: 1
opt.wt_kf_n1: 10 # Multiplier for direct neighbor
opt.wt_kf_n23: 2 # Divisor for neighbor 2,3 (reference is weight of n1)
opt.wt_kf_n45: 3 # Divisor for neighbor 4,5 (reference is weight of n1)

#--------------------------------------------------------------------------------------------
# Visualization
#--------------------------------------------------------------------------------------------

vis.active: 1 # activate / deactivate visualization

# activate different visualization items
vis.showcovgraph: 1
vis.showlandmarks: 1
vis.showtraj: 1
vis.showkeyframes: 1
vis.displaytype: 1   # 0:white 1:intensity 2:color 3:color diff per client

vis.covgraph_minweight: 10 # min. weight of covisibility edges to be displayed
vis.covgraph_shared_edges_only: 1 # only display covisibility edges between trajectories from different agents

vis.scalefactor: 1.0 # scale the visalized map by this factor

# ROS marker sizes
vis.trajmarkersize: 0.08
vis.covmarkersize: 0.008
vis.loopmarkersize: 0.05
vis.camsize: 0.1
vis.camlinesize: 0.01

# Colors for agents
vis.colorR0: 0.55
vis.colorG0: 0.83
vis.colorB0: 0.78

vis.colorR1: 1.00
vis.colorG1: 1.00
vis.colorB1: 0.70

vis.colorR2: 0.75
vis.colorG2: 0.73
vis.colorB2: 0.85

vis.colorR3: 0.98
vis.colorG3: 0.50
vis.colorB3: 0.45

vis.colorR4: 0.50
vis.colorG4: 0.69
vis.colorB4: 0.83

vis.colorR5: 0.99
vis.colorG5: 0.71
vis.colorB5: 0.38

vis.colorR6: 0.70
vis.colorG6: 0.87
vis.colorB6: 0.41

vis.colorR7: 0.99
vis.colorG7: 0.80
vis.colorB7: 0.90

vis.colorR8: 0.85
vis.colorG8: 0.85
vis.colorB8: 0.85

vis.colorR9: 0.74
vis.colorG9: 0.50
vis.colorB9: 0.74

vis.colorR10: 0.80
vis.colorG10: 0.92
vis.colorB10: 0.77

vis.colorR11: 1.00
vis.colorG11: 0.93
vis.colorB11: 0.44

# Colors for covisibility graph edges
vis.colorRcov: 0.6
vis.colorGcov: 0.6
vis.colorBcov: 0.6
