# Data path. adjust them!
common:
    image_file: "/home/lqh/ros/r3live_ws/output/frames/img/0/1627807357.381526.png"
    pcd_file: "/home/lqh/ros/r3live_ws/output/frames/pcd_large/0/1627807357.700470.pcd"
    result_file: "/media/lqh/WDC/dataset/livox_cam/calib/extrinsic.txt"
    # image_file: "/media/lqh/WDC/dataset/livox_cam/image/0.png"
    # pcd_file: "/media/lqh/WDC/dataset/livox_cam/pcd/0.pcd"
    # result_file: "/media/lqh/WDC/dataset/livox_cam/calib/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [863.4241, 0.0, 640.6808,
      0.0,  863.4171, 518.3392,
      0.0, 0.0, 1.0 ] 
    dist_coeffs: [0.0958277, -0.198233, -0.000147133, -0.000430056, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/lqh/ros/r3live_ws/src/mersys/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
